// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace NwOrdersAPI.Entities
{
    // Customers
    public class Customer
    {
        public string CustomerId { get; set; } // CustomerID (Primary key) (length: 5)
        public string CompanyName { get; set; } // CompanyName (Primary key) (length: 40)
        public string? ContactName { get; set; } // ContactName (length: 30)
        public string? ContactTitle { get; set; } // ContactTitle (length: 30)
        public string? Address { get; set; } // Address (length: 60)
        public string City { get; set; } // City (length: 15)
        public string? Region { get; set; } // Region (length: 15)
        public string? PostalCode { get; set; } // PostalCode (length: 10)
        public string Country { get; set; } // Country (length: 15)
        public string? Phone { get; set; } // Phone (length: 24)
        public string? Fax { get; set; } // Fax (length: 24)
    }

}
// </auto-generated>
