// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore.Design;

namespace NwOrdersAPI
{
    public class NwDbContextFactory : IDesignTimeDbContextFactory<NwDbContext>
    {
        public NwDbContext CreateDbContext(string[] args)
        {
            return new NwDbContext();
        }
    }
}
// </auto-generated>
